- name: Create Gitlab directory
  file:
    path: "{{ containers_path }}/gitlab/"
    state: directory

- name: Start Gitlab service
  community.general.docker_container:
    name: gitlab
    image: ulm0/gitlab
    restart_policy: unless-stopped
    container_default_behavior: compatibility
    state: started
    ports:
      - 9080:9080
      - 9443:443
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    env:
      GITLAB_ROOT_PASSWORD: gitlabgitlab
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://192.168.1.30:9080"
