- name: Create Unbound directory
  file:
    path: "{{ containers_path }}/unbound/"
    state: directory

- name: Copy Unbound `Dockerfile`
  copy:
    src: unbound/Dockerfile
    dest: "{{ containers_path }}/unbound/Dockerfile"

- name: Copy Unbound `root.key`
  copy:
    src: files/unbound-root.key
    dest: "{{ containers_path }}/unbound/root.key"

- name: Template `unbound.conf`
  template:
    src: templates/unbound_conf.j2
    dest: "{{ containers_path }}/unbound/unbound.conf"
  vars:
    envs: "{{ unbound_config }}"

- name: Build Unbound image
  community.general.docker_image:
    build:
      path: "{{ containers_path }}/unbound/"
      pull: no
    name: unbound
    source: build

